//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class factors_name_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factors_name_table()
        {
            this.items_in_factor_table = new HashSet<items_in_factor_table>();
        }       
        [Key]
        public int fn_id { get; set; }
        //[Required]
        public string fn_name { get; set; }
        public int module_id { get; set; }
    
        public virtual list_module_name_table list_module_name_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<items_in_factor_table> items_in_factor_table { get; set; }
    }
}
