//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class items_in_factor_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public items_in_factor_table()
        {
            this.test_scenario_table = new HashSet<test_scenario_table>();
        }
        
        [Key]
        public int iif_id { get; set; }
        [Required]
        public string item { get; set; }
        public int fn_id { get; set; }
    
        public virtual factors_name_table factors_name_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_scenario_table> test_scenario_table { get; set; }
    }
}
