//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_scenario_table
    {
        public int test_scenario_id { get; set; }
        public string scenario_message { get; set; }
        public int test_case_id { get; set; }
        public int iif_id { get; set; }
    
        public virtual items_in_factor_table items_in_factor_table { get; set; }
        public virtual test_case_table test_case_table { get; set; }
    }
}
